// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/localDb/genre_id.dart';
import 'core/localDb/movie_entity_db.dart';
import 'core/localDb/search_params.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2803994607678340916),
    name: 'MovieEntityFavouritesDB',
    lastPropertyId: const obx_int.IdUid(9, 4347381242447255918),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2401130013179924999),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6351778886595632537),
        name: 'movieId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6830153942400246489),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2943442302248815631),
        name: 'year',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7517620283836500382),
        name: 'genre',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6865554595340558249),
        name: 'rating',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 483172567678594157),
        name: 'posterUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4347381242447255918),
        name: 'overview',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8806560148796776581),
    name: 'SearchParamsDB',
    lastPropertyId: const obx_int.IdUid(2, 7144307519813828545),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6621743320553871128),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7144307519813828545),
        name: 'query',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 3768629562089895117),
    name: 'GenreId',
    lastPropertyId: const obx_int.IdUid(3, 8477637662032197768),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 90604078526529061),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5748380227674069951),
        name: 'genre',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8477637662032197768),
        name: 'remoteId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 3768629562089895117),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [1193603362823969227, 1411064573443002520],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      5867977697159134884,
      9061392695467037963,
      4899534604845088015,
      7879034660825917786,
      5694165527722285920,
      3813042403346606584,
      1161109340050046575,
      3080924049634639269,
      3620185191613099233,
      1655315589037065420,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MovieEntityFavouritesDB: obx_int.EntityDefinition<MovieEntityFavouritesDB>(
      model: _entities[0],
      toOneRelations: (MovieEntityFavouritesDB object) => [],
      toManyRelations: (MovieEntityFavouritesDB object) => {},
      getId: (MovieEntityFavouritesDB object) => object.id,
      setId: (MovieEntityFavouritesDB object, int id) {
        object.id = id;
      },
      objectToFB: (MovieEntityFavouritesDB object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final yearOffset = fbb.writeString(object.year);
        final genreOffset = fbb.writeString(object.genre);
        final posterUrlOffset = fbb.writeString(object.posterUrl);
        final overviewOffset = fbb.writeString(object.overview);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.movieId);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, yearOffset);
        fbb.addOffset(4, genreOffset);
        fbb.addFloat64(5, object.rating);
        fbb.addOffset(6, posterUrlOffset);
        fbb.addOffset(8, overviewOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final movieIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final yearParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final genreParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final ratingParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final posterUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final overviewParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final object = MovieEntityFavouritesDB(
          id: idParam,
          movieId: movieIdParam,
          title: titleParam,
          year: yearParam,
          genre: genreParam,
          rating: ratingParam,
          posterUrl: posterUrlParam,
          overview: overviewParam,
        );

        return object;
      },
    ),
    SearchParamsDB: obx_int.EntityDefinition<SearchParamsDB>(
      model: _entities[1],
      toOneRelations: (SearchParamsDB object) => [],
      toManyRelations: (SearchParamsDB object) => {},
      getId: (SearchParamsDB object) => object.id,
      setId: (SearchParamsDB object, int id) {
        object.id = id;
      },
      objectToFB: (SearchParamsDB object, fb.Builder fbb) {
        final queryOffset = fbb.writeString(object.query);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, queryOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final queryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = SearchParamsDB(id: idParam, query: queryParam);

        return object;
      },
    ),
    GenreId: obx_int.EntityDefinition<GenreId>(
      model: _entities[2],
      toOneRelations: (GenreId object) => [],
      toManyRelations: (GenreId object) => {},
      getId: (GenreId object) => object.id,
      setId: (GenreId object, int id) {
        object.id = id;
      },
      objectToFB: (GenreId object, fb.Builder fbb) {
        final genreOffset = fbb.writeString(object.genre);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, genreOffset);
        fbb.addInt64(2, object.remoteId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final remoteIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final genreParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = GenreId(
          id: idParam,
          remoteId: remoteIdParam,
          genre: genreParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MovieEntityFavouritesDB] entity fields to define ObjectBox queries.
class MovieEntityFavouritesDB_ {
  /// See [MovieEntityFavouritesDB.id].
  static final id = obx.QueryIntegerProperty<MovieEntityFavouritesDB>(
    _entities[0].properties[0],
  );

  /// See [MovieEntityFavouritesDB.movieId].
  static final movieId = obx.QueryIntegerProperty<MovieEntityFavouritesDB>(
    _entities[0].properties[1],
  );

  /// See [MovieEntityFavouritesDB.title].
  static final title = obx.QueryStringProperty<MovieEntityFavouritesDB>(
    _entities[0].properties[2],
  );

  /// See [MovieEntityFavouritesDB.year].
  static final year = obx.QueryStringProperty<MovieEntityFavouritesDB>(
    _entities[0].properties[3],
  );

  /// See [MovieEntityFavouritesDB.genre].
  static final genre = obx.QueryStringProperty<MovieEntityFavouritesDB>(
    _entities[0].properties[4],
  );

  /// See [MovieEntityFavouritesDB.rating].
  static final rating = obx.QueryDoubleProperty<MovieEntityFavouritesDB>(
    _entities[0].properties[5],
  );

  /// See [MovieEntityFavouritesDB.posterUrl].
  static final posterUrl = obx.QueryStringProperty<MovieEntityFavouritesDB>(
    _entities[0].properties[6],
  );

  /// See [MovieEntityFavouritesDB.overview].
  static final overview = obx.QueryStringProperty<MovieEntityFavouritesDB>(
    _entities[0].properties[7],
  );
}

/// [SearchParamsDB] entity fields to define ObjectBox queries.
class SearchParamsDB_ {
  /// See [SearchParamsDB.id].
  static final id = obx.QueryIntegerProperty<SearchParamsDB>(
    _entities[1].properties[0],
  );

  /// See [SearchParamsDB.query].
  static final query = obx.QueryStringProperty<SearchParamsDB>(
    _entities[1].properties[1],
  );
}

/// [GenreId] entity fields to define ObjectBox queries.
class GenreId_ {
  /// See [GenreId.id].
  static final id = obx.QueryIntegerProperty<GenreId>(
    _entities[2].properties[0],
  );

  /// See [GenreId.genre].
  static final genre = obx.QueryStringProperty<GenreId>(
    _entities[2].properties[1],
  );

  /// See [GenreId.remoteId].
  static final remoteId = obx.QueryIntegerProperty<GenreId>(
    _entities[2].properties[2],
  );
}
